image:
  - Ubuntu
 
build_script:
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt update
  - sudo apt install git build-essential make cmake libtool bsdmainutils autotools-dev autoconf pkg-config automake python3 curl g++-multilib patch g++-mingw-w64-x86-64 -y
  - sudo git clone https://github.com/phoenixkonsole/transcendence.git
  - cd transcendence
  - echo "1"| sudo update-alternatives --config x86_64-w64-mingw32-g++
  - PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
  - cd depends
  - sudo make HOST=x86_64-w64-mingw32
  - cd ..
  - sudo ./autogen.sh
  - sudo ./configure --disable-tests --prefix=$PWD/transcendence/depends/x86_64-w64-mingw32
  - sudo make

after_build:
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\qt
  - sudo mkdir transcendence-%APPVEYOR_REPO_TAG_NAME%
  - sudo cp *.exe transcendence-%APPVEYOR_REPO_TAG_NAME%
  - sudo cp ..\..\..\LICENSE bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - sudo 7z a transcendence-%APPVEYOR_REPO_TAG_NAME%-windows.zip bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - sudo cp transcendence-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: Transcendence-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: TranscendenceRelease

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Et6vQSczqAYwxWaphlKbymjIB3d16tJIwEHXAjxcxDMBxF+HM4bNQEuBIlEzYfU8
    repository: IB313184/transcendence
    artifact: TranscendenceRelease
    draft: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true
