os: Ubuntu

cache: c:\users\appveyor\clcache

before_build:
  - clcache -s

build_script:
  - apt update && apt upgrade
  - apt install git build-essential make cmake libtool bsdmainutils autotools-dev autoconf pkg-config automake python3 curl g++-multilib patch g++-mingw-w64-x86-64
  - git clone https://github.com/phoenixkonsole/transcendence.git
  - cd transcendence
  - PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
  - cd depends
  - make HOST=x86_64-w64-mingw32
  - cd ..
  - ./autogen.sh
  - ./configure --disable-tests --prefix=$PWD/transcendence/depends/x86_64-w64-mingw32
  - make

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\qt
  - mkdir transcendence-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe transcendence-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - 7z a transcendence-%APPVEYOR_REPO_TAG_NAME%-windows.zip bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy transcendence-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: Transcendence-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: TranscendenceRelease

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Et6vQSczqAYwxWaphlKbymjIB3d16tJIwEHXAjxcxDMBxF+HM4bNQEuBIlEzYfU8
    repository: IB313184/transcendence
    artifact: TranscendenceRelease
    draft: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true
